trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Test, running!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Starter pipeline
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    azureSubscription: 'Azure subscription 1(22801d50-8d1e-48ab-a673-396c0cd9c277)'
    Destination: 'AzureBlob'
    storage: 'kopylmykola'
    ContainerName: 'test'